// <auto-generated />
using System;
using EnglishUpgradeApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishUpgradeApi.Migrations
{
    [DbContext(typeof(EnglishTutoringContext))]
    partial class EnglishTutoringContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EnglishUpgradeApi.Models.Score", b =>
                {
                    b.Property<int>("Idscores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idscores");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idscores"), 1L, 1);

                    b.Property<int?>("Comprehension")
                        .HasColumnType("int")
                        .HasColumnName("comprehension");

                    b.Property<int?>("Fluency")
                        .HasColumnType("int")
                        .HasColumnName("fluency");

                    b.Property<int?>("Iduser")
                        .HasColumnType("int")
                        .HasColumnName("iduser");

                    b.Property<int?>("Monolingualism")
                        .HasColumnType("int")
                        .HasColumnName("monolingualism");

                    b.Property<int?>("OverAllEnglish")
                        .HasColumnType("int")
                        .HasColumnName("overAllEnglish");

                    b.Property<int?>("Pronunciation")
                        .HasColumnType("int")
                        .HasColumnName("pronunciation");

                    b.Property<int?>("SentenceStructure")
                        .HasColumnType("int")
                        .HasColumnName("sentenceStructure");

                    b.Property<int?>("Spelling")
                        .HasColumnType("int")
                        .HasColumnName("spelling");

                    b.Property<string>("YearParticipate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("yearParticipate");

                    b.HasKey("Idscores");

                    b.HasIndex("Iduser");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("EnglishUpgradeApi.Models.User", b =>
                {
                    b.Property<int>("Iduser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iduser");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iduser"), 1L, 1);

                    b.Property<string>("Companyrank")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("companyrank");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("email");

                    b.Property<string>("Grouprank")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("grouprank");

                    b.Property<string>("Level")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("level");

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("username");

                    b.HasKey("Iduser")
                        .HasName("PK_Usuario");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("EnglishUpgradeApi.Models.Score", b =>
                {
                    b.HasOne("EnglishUpgradeApi.Models.User", "IduserNavigation")
                        .WithMany("Scores")
                        .HasForeignKey("Iduser")
                        .HasConstraintName("FK__Scores__idusuari__02084FDA");

                    b.Navigation("IduserNavigation");
                });

            modelBuilder.Entity("EnglishUpgradeApi.Models.User", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
